steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'party-app'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '3600'
      - '--set-secrets=BUCKET_NAME=BUCKET_NAME:latest,GOOGLE_CLOUD_PROJECT=PROJECT_ID:latest'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY