steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'party-app'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '3600'
      # The secret is here:
      - '--set-secrets=BUCKET_NAME=BUCKET_NAME:latest'
      # The project ID is here as a regular variable:
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=partyphotos-501522'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY